trigger:
- master

pool:
  vmImage: 'macos-10.14'

steps:
- script: |
    echo "Xcode version:"
    xcodebuild -version
  displayName: 'Show Xcode version'

- script: |
    echo "Simulators:"
    xcrun simctl list devices
  displayName: 'Show installed simulators'

- script: |
    ls -alt /Applications
  displayName: "Show Applications folder contents"