trigger:
- master

pool:
  vmImage: 'macos-10.14'

steps:
- script: |
    echo "Xcode version:"
    xcodebuild -version
  displayName: 'Show Xcode version'

- script: |
    echo "Simulators:"
    xcrun simctl list devices
  displayName: 'Show installed simulators'

- task: email@0
  inputs:
    emailConfigFile: 
    emailFrom: 'v-andrem@microsoft.com'
    emailTo: 'v-ivnosa@microsoft.com'
    emailSubject: 'Hello from Azure DevOps'
    emailBody: 'kuku'