trigger:
- master

pool:
  vmImage: 'macos-10.15'

steps:
- script: |
    echo "Xcode version:"
    xcodebuild -version
  displayName: 'Show Xcode version'

- script: |
    echo "Simulators:"
    xcrun simctl list devices
  displayName: 'Show installed simulators'
  condition: and(succeeded(), eq(variables['RunTests'], "true"))

- script: |
    sudo xcode-select -s /Applications/Xcode_12.app
  displayName: 'Select Xcode 12'

- script: |
    xcrun xcodebuild -version
  displayName: "Print Xcode version"

- script: |
    ls -alt /Applications
  displayName: "Show Applications folder contents"